<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IsPackable>true</IsPackable>
        <Product>I18Next.Net</Product>
        <Authors>Mahdi Ghorban Pour</Authors>
        <Company>Mahdi Ghorban Pour</Company>
        <Version>1.0.2</Version>
        <RepositoryUrl>https://github.com/mahdighorbanpour/I18Next.Net.Version4</RepositoryUrl>
        <PackageProjectUrl>https://github.com/mahdighorbanpour/I18Next.Net.Version4</PackageProjectUrl>
        <PackageId>I18Next.Net.Gettext.Version4</PackageId>
        <RepositoryType>git</RepositoryType>
        <LangVersion>latest</LangVersion>
        <NoWarn>CS1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DocumentationFile>bin\Debug\I18Next.Net.Gettext.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\I18Next.Net.Gettext.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\I18Next.Net.Abstractions\I18Next.Net.Abstractions.csproj" />
      <ProjectReference Include="..\I18Next.Net\I18Next.Net.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NGettext" Version="0.6.7" />
    </ItemGroup>

</Project>
