<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <RepositoryUrl>https://github.com/mahdighorbanpour/I18Next.Net.Version4</RepositoryUrl>
        <PackageProjectUrl>https://github.com/mahdighorbanpour/I18Next.Net.Version4</PackageProjectUrl>
        <PackageId>I18Next.Net.Version4</PackageId>
        <IsPackable>true</IsPackable>
        <Version>1.0.2</Version>
        <Authors>Mahdi Ghorban Pour</Authors>
        <RepositoryType>git</RepositoryType>
        <LangVersion>latest</LangVersion>
        <NoWarn>CS1591</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DocumentationFile>bin\Debug\I18Next.Net.xml</DocumentationFile>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DocumentationFile>bin\Release\I18Next.Net.xml</DocumentationFile>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\I18Next.Net.Abstractions\I18Next.Net.Abstractions.csproj" />
    </ItemGroup>
</Project>
